"""add password_hash to users

Revision ID: 56161a082a85
Revises: <revision>
Create Date: 2026-09-01 03:41:28.550507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56161a082a85'
down_revision: Union[str, Sequence[str], None] = '<revision>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.create_unique_constraint(None, 'documents', ['file_name'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=True)
    # ### end Alembic commands ###
