"""add avatar_url and face_embedding to users

Revision ID: fbf0fd0183c8
Revises: 56161a082a85
Create Date: 2026-09-01 04:34:29.438939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf0fd0183c8'
down_revision: Union[str, Sequence[str], None] = '56161a082a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embedding')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
